#!/bin/sh
# chkconfig: 234 20 80
# description: DeployService basic start/shutdown script
# processname: deployservice

DIRBASE="/opt/deployservice"

start() {
echo "Starting deployservice... "
cd $DIRBASE
./deployservice.sh
echo "done."

}
stop() {
echo -n "Shutting down deployservice: "

APP_NAME=deployservice
APP_ID=`ps -FC java |grep $APP_NAME| awk 'BEGIN{FS="[ :]+"}{print $2}' |awk 'FNR == 1'`
KILL_APP="kill -9 $APP_ID"
${KILL_APP}

echo "done."
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac
exit 0
