CREATE TABLE ts$events (
  NAME VARCHAR2(255 CHAR) NOT NULL,
  DUE_DATE TIMESTAMP NOT NULL,
  DATA CLOB,
  FIRED VARCHAR(5 CHAR) DEFAULT '0'
);

CREATE INDEX TS$EVENTS_DUEDATE ON ts$events (DUE_DATE);
CREATE INDEX TS$EVENTS_FIRED ON ts$events(FIRED);