/*
 * generated by Xtext
 */
package org.monet.editor.dsl;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.monet.editor.dsl.configuration.CustomOutputConfigurationProvider;
import org.monet.editor.dsl.generator.FixedModelGenerator;
import org.monet.editor.dsl.helper.TypeRefCache;
import org.monet.editor.dsl.helper.TypeRefCacheImpl;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MonetLocalizationLanguageRuntimeModule extends org.monet.editor.dsl.AbstractMonetLocalizationLanguageRuntimeModule {

  public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
    return FixedModelGenerator.class;
  }
  
  public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
    return CustomOutputConfigurationProvider.class;
  }
  
  @Override
  public void configure(Binder binder) {
    super.configure(binder);
    
    binder.bind(TypeRefCache.class).to(TypeRefCacheImpl.class);
  }
  
}
