/*
* generated by Xtext
*/
package org.monet.editor.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MonetModelingLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.monet.editor.dsl.ui.internal.MonetLocalizationLanguageActivator.getInstance().getInjector("org.monet.editor.dsl.MonetModelingLanguage");
	}
	
}
