/*
* generated by Xtext
*/
package org.monet.editor.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MonetModelingLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/monet/editor/dsl/parser/antlr/internal/InternalMonetModelingLanguage.tokens");
	}
}
