/*
* generated by Xtext
*/
package org.monet.editor.dsl.ui.contentassist;

import java.util.HashMap;
import java.util.Map.Entry;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.monet.editor.util.LanguageUtil;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MonetLocalizationLanguageProposalProvider extends AbstractMonetLocalizationLanguageProposalProvider {
  
  public void completeDomainModel_Code(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
    super.completeDomainModel_Code(model, assignment, context, acceptor);
    
    acceptor.accept(createCompletionProposal("default", context));
    
    HashMap<String, String> languages = LanguageUtil.getLanguages();
    for(Entry<String, String> language : languages.entrySet()) {
      String code = language.getKey();
      String label = language.getValue();
      acceptor.accept(createCompletionProposal(code, code + " : " + label, null, context));
    }
  };
  
}
