/*
* generated by Xtext
*/
package org.monet.editor.dsl.ui.contentassist;

import java.util.ArrayList;
import java.util.HashSet;

import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalPostProcessor;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MonetModelingLanguageCompletionProposalPostProcessor implements ICompletionProposalPostProcessor {

  @Override
  public ICompletionProposal[] postProcess(ICompletionProposal[] proposals) {
    return this.removeDuplicates(proposals);
  }
  
  private ICompletionProposal[] removeDuplicates(ICompletionProposal[] proposals) {
    ArrayList<ICompletionProposal> result = new ArrayList<ICompletionProposal>();
    HashSet<String> proposalsParsed = new HashSet<String>();
    
    for (int i=0; i<proposals.length; i++) {
      ICompletionProposal proposal = proposals[i];
      String displayString = proposal.getDisplayString();
      
      if (proposalsParsed.contains(displayString))
        continue;
      
      proposalsParsed.add(displayString);
      result.add(proposal);
    }
    
    return result.toArray(new ICompletionProposal[0]);
  }
  
}
