/*
 * generated by Xtext
 */
package org.monet.editor.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MonetLocalizationLanguageUiModule extends org.monet.editor.dsl.ui.AbstractMonetLocalizationLanguageUiModule {
	public MonetLocalizationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
