/*
* generated by Xtext
*/
package org.monet.editor.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;
import org.monet.editor.dsl.helper.XtendHelper;
import org.monet.editor.dsl.metamodel.Item;
import org.monet.editor.dsl.metamodel.MetaModelStructure;
import org.monet.editor.dsl.monetModelingLanguage.Property;

import com.google.inject.Inject;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class MonetModelingLanguageDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

  @Inject
  private MetaModelStructure structure;

  protected String text(Property o) {
    Item item = XtendHelper.checkElement(o, this.structure);
    return item.getDescription();
  }
  
}
