/*
 * generated by Xtext
 */
package org.monet.editor.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.monet.editor.dsl.ui.internal.MonetLocalizationLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MonetModelingLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MonetLocalizationLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MonetLocalizationLanguageActivator.getInstance().getInjector(MonetLocalizationLanguageActivator.ORG_MONET_EDITOR_DSL_MONETMODELINGLANGUAGE);
	}
	
}
