package org.monet.federation.accountoffice.core.layers.auth.impl.micv.sessioninternal;


/*
    Monet will assist business to process re-engineering. Monet separate the
    business logic from the underlying technology to allow Model-Driven
    Engineering (MDE). These models guide all the development process over a
    Service Oriented Architecture (SOA).

    Copyright (C) 2009  Grupo de Ingenieria del Sofware y Sistemas de la Universidad de Las Palmas de Gran Canaria

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.
*/

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilaci�n R1)
// Generated source version: 1.1.3




public class Sesion_WebServicePortType_comprobar_validez_sesion_RequestStruct {
    protected java.lang.String identificador_sesion;
    protected java.lang.String dni_usuario;
    
    public Sesion_WebServicePortType_comprobar_validez_sesion_RequestStruct() {
    }
    
    public Sesion_WebServicePortType_comprobar_validez_sesion_RequestStruct(java.lang.String identificador_sesion, java.lang.String dni_usuario) {
        this.identificador_sesion = identificador_sesion;
        this.dni_usuario = dni_usuario;
    }
    
    public java.lang.String getIdentificador_sesion() {
        return identificador_sesion;
    }
    
    public void setIdentificador_sesion(java.lang.String identificador_sesion) {
        this.identificador_sesion = identificador_sesion;
    }
    
    public java.lang.String getDni_usuario() {
        return dni_usuario;
    }
    
    public void setDni_usuario(java.lang.String dni_usuario) {
        this.dni_usuario = dni_usuario;
    }
}
