package org.monet.federation.accountoffice.core.layers.auth.impl.micv.sessioninternal;
/*
    Monet will assist business to process re-engineering. Monet separate the
    business logic from the underlying technology to allow Model-Driven
    Engineering (MDE). These models guide all the development process over a
    Service Oriented Architecture (SOA).

    Copyright (C) 2009  Grupo de Ingenieria del Sofware y Sistemas de la Universidad de Las Palmas de Gran Canaria

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.
*/

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilaci�n R1)
// Generated source version: 1.1.3



public class Sesion_WebServicePortType_comprobar_validez_sesion_ResponseStruct {
    protected java.lang.String _return;
    
    public Sesion_WebServicePortType_comprobar_validez_sesion_ResponseStruct() {
    }
    
    public Sesion_WebServicePortType_comprobar_validez_sesion_ResponseStruct(java.lang.String _return) {
        this._return = _return;
    }
    
    public java.lang.String get_return() {
        return _return;
    }
    
    public void set_return(java.lang.String _return) {
        this._return = _return;
    }
}
