package client.services;

import client.services.translators.TaskTranslator;
import cosmos.services.translators.DateTranslator;
import cosmos.services.translators.ListTranslator;
import cosmos.types.Date;

public interface TranslatorService extends Service, cosmos.services.TranslatorService, ListTranslator, TaskTranslator, DateTranslator {

	enum Label {
		DELETE, SEARCH, SEARCH_RESULTS_FOR, PUBLISH, LIST_EMPTY, SHOW_LIST_ITEMS, LOADING, TITLE, DOWNLOAD,
		TASK_LIST, NEWS, TRASH, HISTORY, BACK, UP, PREVIOUS, NEXT, LINK, YES, NO, OTHER, YEAR,
		MONTH, DAY, HOUR, MINUTE, SECOND, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY,
		SATURDAY, SUNDAY, DATE_PARSER, MEMBERS, EMPTY_MEMBERS, NOTIFICATIONS, EMPTY_NOTIFICATIONS,
		ONE_HOUR, ONE_DAY, ONE_MONTH, ONE_YEAR, INCREMENT_ONE_HOUR, INCREMENT_ONE_DAY, INCREMENT_ONE_MONTH,
		INCREMENT_ONE_YEAR, DECREMENT_ONE_HOUR, DECREMENT_ONE_DAY, DECREMENT_ONE_MONTH, DECREMENT_ONE_YEAR, NO_VALUE,
		WELCOME, CREATE_DATE, UPDATE_DATE, URGENT, ALL, ALIVE, ACTIVE, PENDING, FINISHED, OPTIONS, RECENT_OPTIONS, ALLOW_LESS_PRECISION,
		STATE, PREVIEW, NO_LABEL, IMAGE_TOO_BIG, SHOW_SECTION, HIDE_SECTION, ADD_NODE, ADD_COMPOSITE_NODE, NONE, ADD_ORDER,
		HELPER, SHOW_ELEMENT, CLICK_TO_CONFIRM, DOCUMENT_LOAD_SECONDS_REMAINING, SEARCHING, DESCRIPTION;

		@Override
		public String toString() {
			return super.toString().replace("_", "-").toLowerCase();
		}
	}

	enum ErrorLabel {
		TITLE, USER_NOT_LOGGED, TEXT_FIELD_LENGTH, TEXT_FIELD_PATTERN, DATE_FIELD_RANGE, SOURCE_OPTIONS, INDEX_OPTIONS, SAVE_NOTES, UPLOADING,
		SAVE_VALUE, ADD_FIELD, CHANGE_FIELD_ORDER, DELETE_FIELD, CLEAR_FIELD, FILE_SIZE, MAX_NUMBER_OF_FIELDS, WARNING;

		@Override
		public String toString() {
			return super.toString().replace("_", "-").toLowerCase();
		}
	}

	enum OperationLabel {
		ADD, SHOW_NEWS, SHOW_HISTORY, SHOW_TASK_LIST, SHOW_TRASH, SHOW_NOTIFICATION_LIST, SHOW_BUSINESS_UNIT_LIST,
		DELETE_SELECTION, LOGOUT, TOGGLE_LAYOUT_MODE, TOGGLE_TASK_URGENT, UPLOAD, UPLOADING, SET_TASKS_OWNER_SELECTION,
		UN_SET_TASKS_OWNER_SELECTION, UN_SET_TASK_OWNER, ABORT_TASK, SETUP_TASK_DELEGATION,
		SHOW_COMPOSITE_FIELDS, SHOW_MORE_FIELDS, SHOW_LESS_FIELDS, SELECT_TASK_DELEGATION_ROLE,
		SOLVE_TASK_LINE, SOLVE_TASK_EDITION, SHOW_HOME, SHOW_TASK_VIEW, CROP_IMAGE, RESTORE, SHOW_FULL_SIZE, ACCEPT, CANCEL,
		REFRESH_TASK, REFRESH_ACCOUNT, CLOSE_DIALOG, CONFIRM, CONFIRM_DELETE_NODE, CONFIRM_DELETE_NODES, TOGGLE_HELPER, HIDE_HELPER;

		@Override
		public String toString() {
			return super.toString().replace("_", "-").toLowerCase();
		}
	}

	enum ListLabel {
		MODE_LIST, MODE_ICON, ALL, MORE_THAN_ONE, FILTER_MESSAGE_WHEN_EMPTY, MESSAGE_WHEN_EMPTY,
		SELECT_ELEMENT, SELECT_ALL, SELECT_NONE, SELECT_INVERT, DELETE;

		@Override
		public String toString() {
			return super.toString().replace("_", "-").toLowerCase();
		}
	}

	String getLoadingLabel();

	String getNoPhoto();

	String getAddPhoto();

	String translateSavedPeriodAgo(String message, Date date);

	String translateSearchForCondition(String condition);

	String translateCountDate(Date date);

}
