DROP TABLE IF EXISTS `components`;

CREATE TABLE `components` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT(20) DEFAULT NULL,
  `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `type` TINYINT(4) DEFAULT NULL,
  `model_version_id` BIGINT(20) DEFAULT NULL,
  `state` INT(2) NOT NULL,
  `running_time` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `models`;

CREATE TABLE `models` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(120) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `modelversions`;

CREATE TABLE `modelversions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `model_id` BIGINT(20) NOT NULL,
  `label` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `metamodel_version` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `servers`;

CREATE TABLE `servers` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `ip` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
