PROMPT Adding DEFINITION_TYPE column on ts$nodes ...
ALTER TABLE ts$nodes ADD DEFINITION_TYPE VARCHAR(100) NOT NULL, ADD KEY (DEFINITION_TYPE);

TRUNCATE TABLE ts$nodes_revisions;
ALTER TABLE ts$nodes_revisions ADD COLUMN ID INT(11) NOT NULL;
ALTER TABLE ts$nodes_revisions ADD PRIMARY KEY (ID);
ALTER TABLE ts$nodes_revisions MODIFY COLUMN ID INT(11) NOT NULL AUTO_INCREMENT;

DROP TABLE ts$users_roles;

CREATE TABLE `ts$roles` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USER` INT(11) NOT NULL,
  `CODE` VARCHAR(255) NOT NULL,
  `BEGIN_DATE` TIMESTAMP NOT NULL,
  `EXPIRE_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`),
  KEY `TS$ROLES_IDUSER` (`ID_USER`),
  KEY `TS$ROLES_CODE` (`CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE ts$users ADD FULLTEXT TS$USERS_USERNAME_FULLTEXT (username);

DELIMITER $$

DROP PROCEDURE IF EXISTS `renamethesauruscolumn`$$
CREATE PROCEDURE `renamethesauruscolumn`()
BEGIN
  DECLARE done INT;
  DECLARE databasename TEXT;
  DECLARE itemname VARCHAR(60);
  DECLARE sqlcommand VARCHAR(255);
  DECLARE ListTables CURSOR FOR SELECT `TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA` = databasename AND `TABLE_TYPE` = 'BASE TABLE' AND (table_name LIKE 'tt$%');
  DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET done = 1;    

  SELECT DATABASE() INTO databasename;
  SET FOREIGN_KEY_CHECKS=0;
  
  SET done = 0;
  OPEN ListTables;
  REPEAT
    FETCH ListTables INTO itemname;
    IF NOT done THEN
      SET @underscore_found = LOCATE('_',itemname);
      IF NOT @underscore_found THEN
        SET @s = CONCAT('ALTER TABLE ', itemname, ' CHANGE data tags TEXT;');      
        PREPARE stmt FROM @s;
        EXECUTE stmt;     
      END IF;
      SET @s = CONCAT('ALTER TABLE ', itemname, ' ADD is_new INT(1) NOT NULL DEFAULT 0;');      
      PREPARE stmt FROM @s;
      EXECUTE stmt;     
    END IF;
  UNTIL done END REPEAT;
  CLOSE ListTables;

  SET FOREIGN_KEY_CHECKS=1;
END$$

DELIMITER ;

CALL `renamethesauruscolumn`();
DROP PROCEDURE `renamethesauruscolumn`;

CREATE TABLE `ts$attachments` (
  `ID_SOURCE` INT(11) NOT NULL,
  `ID_TARGET` VARCHAR(255) NOT NULL,
  `TYPE_TARGET` VARCHAR(20) NOT NULL,
  `CODE_TARGET` VARCHAR(100) NOT NULL,
  `DATA` VARCHAR(255) NOT NULL,
  `DELETE_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID_SOURCE`,`ID_TARGET`,`TYPE_TARGET`),
  KEY `TS$ATTACHMENTS_INDEX1` (`ID_SOURCE`),
  KEY `TS$ATTACHMENTSS_INDEX3` (`ID_TARGET`),
  KEY `TS$ATTACHMENTS_INDEX4` (`TYPE_TARGET`),
  KEY `TS$ATTACHMENTS_INDEX5` (`CODE_TARGET`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;